### ISSUE TITLE
There is an error in the formula

### ISSUE THREAD

**Issue by AIR-hl** [LuJunru/SamPO#1]
The gradient of the DPO loss function is $\nabla_{\theta}L_{DPO}=-\beta\sigma(r_l-r_w)\left[\nabla_{\theta}\log \pi(y_w)-\nabla_{\theta}\log \pi(y_l)\right]$，therefore, the form of formula 6 is wrong.

if the $L_{sampo}$ is correct, the $\Delta$ should be $\beta \sigma \left[\sum\limits_{t=1}^{T_m} \log \frac{\pi_{\theta}\left(y_{l}^{t} \mid x\right)}{\pi_{r e f}\left(y_{l}^{t} \mid x\right)} - \sum\limits_{t=1}^{T_m} \log \frac{\pi_{\theta}\left(y_{w}^{t} \mid x\right)}{\pi_{r e f}\left(y_{w}^{t} \mid x\right)}\right]$

**Comment by LuJunru** [comment]
> The gradient of the DPO loss function is ∇θLDPO=−βσ(rl−rw)[∇θlog⁡π(yw)−∇θlog⁡π(yl)]，therefore, the form of formula 6 is wrong.
> 
> if the Lsampo is correct, the Δ should be βσ[∑t=1Tmlog⁡πθ(ylt∣x)πref(ylt∣x)−∑t=1Tmlog⁡πθ(ywt∣x)πref(ywt∣x)]

Hi AIR-hl,

We write formula 5 and 6 in reference to the DPO's paper (https://arxiv.org/pdf/2305.18290), in their section 4 and appendix A.4, in specific. Maybe you can have a double check? 

As for Δ of SamPO in formula 7, we provide proofs in our appendix A.

regards,
Junru

**Comment by AIR-hl** [comment]
> > The gradient of the DPO loss function is ∇θLDPO=−βσ(rl−rw)[∇θlog⁡π(yw)−∇θlog⁡π(yl)]，therefore, the form of formula 6 is wrong.
> > if the Lsampo is correct, the Δ should be βσ[∑t=1Tmlog⁡πθ(ylt∣x)πref(ylt∣x)−∑t=1Tmlog⁡πθ(ywt∣x)πref(ywt∣x)]
> 
> Hi AIR-hl,
> 
> We write formula 5 and 6 in reference to the DPO's paper (https://arxiv.org/pdf/2305.18290), in their section 4 and appendix A.4, in specific. Maybe you can have a double check?
> 
> As for Δ of SamPO in formula 7, we provide proofs in our appendix A.
> 
> regards, Junru

@LuJunru Thank you. The gradiant formula in DPO paper  is as follows:
![QQ_1721873450281](https://github.com/user-attachments/assets/bfd3838d-5541-4cac-9151-7501b6c94a28)

It's clear that the weight item is $βσ(r_l−r_w)$

The gradiant formula in your work is as follows:
![QQ_1721873743611](https://github.com/user-attachments/assets/d07b79ce-5489-43e1-9853-8c9e54cdfbd3)
![QQ_1721873694974](https://github.com/user-attachments/assets/121f0437-9f46-41bc-a6e4-6e697d699691)

It's clear that the weight item is $(r_w-r_l)$, I guess it is different from the weight $\beta\sigma(r_l-rw)$ in the DPO paper.

Please forgive me if there are any mistakes.

**Comment by LuJunru** [comment]
> > > The gradient of the DPO loss function is ∇θLDPO=−βσ(rl−rw)[∇θlog⁡π(yw)−∇θlog⁡π(yl)]，therefore, the form of formula 6 is wrong.
> > > if the Lsampo is correct, the Δ should be βσ[∑t=1Tmlog⁡πθ(ylt∣x)πref(ylt∣x)−∑t=1Tmlog⁡πθ(ywt∣x)πref(ywt∣x)]
> > 
> > 
> > Hi AIR-hl,
> > We write formula 5 and 6 in reference to the DPO's paper (https://arxiv.org/pdf/2305.18290), in their section 4 and appendix A.4, in specific. Maybe you can have a double check?
> > As for Δ of SamPO in formula 7, we provide proofs in our appendix A.
> > regards, Junru
> 
> @LuJunru Thank you. The gradiant formula in DPO paper is as follows: ![QQ_1721873450281](https://private-user-images.githubusercontent.com/66808901/351933241-bfd3838d-5541-4cac-9151-7501b6c94a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzQ2MjEsIm5iZiI6MTcyMTg3NDMyMSwicGF0aCI6Ii82NjgwODkwMS8zNTE5MzMyNDEtYmZkMzgzOGQtNTU0MS00Y2FjLTkxNTEtNzUwMWI2Yzk0YTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyMjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWRjMzJjNjA4OWY1NTg1OTNkN2JkYzkwOGQxYWI4OGE2NTJhMWM3MWQ5YmEwMzg3ZWE4ZWI4MjhkOTVjZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iebw6tz2hAKp09qSRaIgvVh_u63xPp49f2K_iGx7L7Q)
> 
> It's clear that the weight item is βσ(rl−rw)
> 
> The gradiant formula in your work is as follows: ![QQ_1721873743611](https://private-user-images.githubusercontent.com/66808901/351933876-d07b79ce-5489-43e1-9853-8c9e54cdfbd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzQ2MjEsIm5iZiI6MTcyMTg3NDMyMSwicGF0aCI6Ii82NjgwODkwMS8zNTE5MzM4NzYtZDA3Yjc5Y2UtNTQ4OS00M2UxLTk4NTMtOGM5ZTU0Y2RmYmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyMjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYmFhYjZmZjc2ZGJiZDRjYTdkNzdkZDBjMjdiZDhiNTQ3YjkxM2I5YWRkNzJmNzgyNDg3N2IyMGJiM2MxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKV5NYR2QqmYUAckkDUCrYrv-VuUXZuPGMjjtBv4uVA) ![QQ_1721873694974](https://private-user-images.githubusercontent.com/66808901/351933785-121f0437-9f46-41bc-a6e4-6e697d699691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzQ2MjEsIm5iZiI6MTcyMTg3NDMyMSwicGF0aCI6Ii82NjgwODkwMS8zNTE5MzM3ODUtMTIxZjA0MzctOWY0Ni00MWJjLWE2ZTQtNmU2OTdkNjk5NjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyMjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2Y3NDc4ZDJmNjk4MzMyYjUxOTIzMDgyNGQwNDVhNjIzNjkyODhlY2I5Nzg1M2I0Y2FmMjAzNWYyZTQ1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhdqHXp4ebbznWf5Tc4IEprs0t5ShDCbiax6Gyxv4jE)
> 
> It's clear that the weight item is (rw−rl), I guess it is different from the weight βσ(rl−rw) in the DPO paper.
> 
> Please forgive me if there are any mistakes.

@AIR-hl
I am kind of confused actually. The formula 4 of Δ in our work has already contained β, isn't it?

**Comment by AIR-hl** [comment]
> @AIR-hl I am kind of confused actually. The formula 4 of Δ in our work has already contained β, isn't it?

The focus is not on beta, and according to DPO paper, $r_{\theta}(y,x)=\beta \log \frac{\pi_{\theta}(y|x)}{\pi_{ref}(y|x)}$, but in the gradient formula, we will get a additional $beta$ on weight item, so the weight actually is $\beta \sigma (\beta \log \frac{\pi_{\theta}(y_w|x)}{\pi_{ref}(y_w|x)}-\beta \log \frac{\pi_{\theta}(y_l|x)}{\pi_{ref}(y_l|x)})$

The problem I really want to point out is $\sigma$. $\sigma(r_w-r_l)$ is completely different from $(r_w-r_l)$ , and please note that the gradient formula in DPO is $\sigma(r_l-r_w)$, not $\sigma(r_w-r_l)$, their meanings are different

**Comment by LuJunru** [comment]
@AIR-hl 
<img width="1089" alt="A 4" src="https://github.com/user-attachments/assets/e504f44e-ec22-4c65-964f-425b35d03d25">
Ok, I see. So you mean the part in brackets of formula 5 should be  βσ(Δ·M), instead of current Δ·M. Am I right now?

**Comment by AIR-hl** [comment]
> @AIR-hl <img alt="A 4" width="1089" src="https://private-user-images.githubusercontent.com/29519546/351942139-e504f44e-ec22-4c65-964f-425b35d03d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzcwODcsIm5iZiI6MTcyMTg3Njc4NywicGF0aCI6Ii8yOTUxOTU0Ni8zNTE5NDIxMzktZTUwNGY0NGUtZWMyMi00YzY1LTk2NGYtNDI1YjM1ZDAzZDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzMDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMzllY2UyYzI4ZmQ5NjZlNWIwMTc3MDM5MzY0MTU1ODI3YzMxZmM2YjBkMjc3YWJkY2ZiNzVkOTY3YmU2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8txJs02RRVSVSnDIl81jv7q5eS0VP-y7VKBhyAOWzf0"> Ok, I see. So you mean the part in brackets of formula 5 should be βσ(Δ·M), instead of current Δ·M. Am I right now?

if you don't want to change the formula of $\Delta$, the weight item should be $\beta \cdot \sigma(-\Delta) \cdot M$

**Comment by LuJunru** [comment]
> > @AIR-hl <img alt="A 4" width="1089" src="https://private-user-images.githubusercontent.com/29519546/351942139-e504f44e-ec22-4c65-964f-425b35d03d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzcwODcsIm5iZiI6MTcyMTg3Njc4NywicGF0aCI6Ii8yOTUxOTU0Ni8zNTE5NDIxMzktZTUwNGY0NGUtZWMyMi00YzY1LTk2NGYtNDI1YjM1ZDAzZDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzMDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMzllY2UyYzI4ZmQ5NjZlNWIwMTc3MDM5MzY0MTU1ODI3YzMxZmM2YjBkMjc3YWJkY2ZiNzVkOTY3YmU2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8txJs02RRVSVSnDIl81jv7q5eS0VP-y7VKBhyAOWzf0"> Ok, I see. So you mean the part in brackets of formula 5 should be βσ(Δ·M), instead of current Δ·M. Am I right now?
> 
> if you don't want to change the formula of Δ, the weight item should be β⋅σ(−Δ)⋅M

Yes, β⋅σ(Δ)⋅M. I think the screenshot from DPO's appendix A.4 shows y_w is in front of y_l.

**Comment by AIR-hl** [comment]
Please check the derivation,the result in A.4 is wrong, it should be $\sigma(-x)$ rather than $\sgima(x)$
![QQ_1721877312727](https://github.com/user-attachments/assets/22f4bcf8-eb89-4d93-b7a0-ca9caf69c6bd)

the correct formula is on page 5, you can also find it in Simpo's paper
![QQ_1721877426867](https://github.com/user-attachments/assets/94830f80-f903-40df-9603-17e53a7f5e14)

**Comment by LuJunru** [comment]
> Please check the derivation,the result in A.4 is wrong, it should be σ(−x) rather than \sgima(x) ![QQ_1721877312727](https://github.com/user-attachments/assets/22f4bcf8-eb89-4d93-b7a0-ca9caf69c6bd)
> 
> the correct formula is on page 5, you can also find it in Simpo's paper ![QQ_1721877426867](https://private-user-images.githubusercontent.com/66808901/351944727-94830f80-f903-40df-9603-17e53a7f5e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzc5NjAsIm5iZiI6MTcyMTg3NzY2MCwicGF0aCI6Ii82NjgwODkwMS8zNTE5NDQ3MjctOTQ4MzBmODAtZjkwMy00MGRmLTk2MDMtMTdlNTNhN2Y1ZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzMjEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YWZjYzhmZTY0MDRhY2QzY2Y4ZmQ0MzI4ZmE4ODYxMTA5NGQ1OTI3NTQ3OTU3ZDgxNGQzMzAyODIxMzIxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Uh0JE4xwJflnCfXkPTyqgT5AL4Vb0QjrYK3M75oUkg)

Sure. Thank you for the report of mistake. We'll do the correction in next revision version.

**Comment by AIR-hl** [comment]
> Sure. Thank you for the report of mistake. We'll do the correction in next revision version.

You're welcome. In fact, we did similar work to you,  but unfortunately you were faster. (ㄒoㄒ)

**Comment by LuJunru** [comment]
> > Sure. Thank you for the report of mistake. We'll do the correction in next revision version.
> 
> You're welcome. In fact, we did similar work to you, but unfortunately you were faster. (ㄒoㄒ)

🤯
